name: katkode_ai_manager
description: "A flutter library to let users use their own LLM keys to access AI models"
version: 0.0.1
homepage: https://katkode.com
repository: https://github.com/katkodeorg/katkode_ai_manager
topics:
  - katkode
  - ai-manager
  - ai-store
  - ai-key-store
  - llm-key-store

environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_gemini: ^2.0.5
  sembast: ^3.7.3+3
  sembast_web: ^2.4.0+2
  path: ^1.9.0
  path_provider: ^2.1.4
  uuid: ^4.5.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter: